### ISSUE TITLE
First two bundle_ids blank?

### ISSUE THREAD

**Issue by mdlincoln** [cooperhewitt/the-pen-data#1]
`bundle_id` in the first two rows appear to be blank - but nowhere else. Any idea why?

**Comment by micahwalter** [comment]
Most likely these were from testing in the early days of launching the Pen. They should probably be removed from the data set. Thanks for noticing.

**Comment by micahwalter** [comment]
fixed in 6757f2355c1a2c743a6cddb11736decbff412a23
